
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void WriteDFVConfig(void)

{
  int Pointer;
  
  Pointer = TextFileOpen(DFVFilename,&StringTablePointer);
  if (Pointer != 0) {
    TextFileWrite(Pointer,s____DISPLAY_00647540);
    TextFileWrite(Pointer,s_windowed____i_00647528,VID_Windowed);
    TextFileWrite(Pointer,s_hw3d_deviceno____i_00647510,SYS_DeviceNO);
    TextFileWrite(Pointer,s_hw3d_name_____s__006474f4,&GPUInfo);
    TextFileWrite(Pointer,s_hw3d_guid_____s__006474d8,&SYS_GUID);
    TextFileWrite(Pointer,s_hw3d_matchz____i_006474c0,SYS_MatchZ);
    TextFileWrite(Pointer,s_hw3d_res512x384____i_006474a8,_VID_ResolutionSet & 1);
    TextFileWrite(Pointer,s_hw3d_res640x480____i_00647490,_VID_ResolutionSet >> 1 & 1);
    TextFileWrite(Pointer,s_hw3d_res800x600____i_00647478,_VID_ResolutionSet >> 2 & 1);
    TextFileWrite(Pointer,s_hw3d_res1024x768____i_00647460,_VID_ResolutionSet >> 3 & 1);
    TextFileWrite(Pointer,s_hw3d_res1280x1024____i_00647448,_VID_ResolutionSet >> 4 & 1);
    TextFileWrite(Pointer,s_hw3d_res1600x1200____i_00647430,_VID_ResolutionSet >> 5 & 1);
    TextFileWrite(Pointer,s_hw3d_res1920x1440____i_00647418,_VID_ResolutionSet >> 6 & 1);
    TextFileWrite(Pointer,s_hw3d_res2048x1536____i_00647400,_VID_ResolutionSet >> 7 & 1);
    TextFileWrite(Pointer,s_game_res____i_006473e8,VID_Resolution);
    TextFileWrite(Pointer,s_gamma_____1f_006473cc,(double)VID_Gamma);
    TextFileWrite(Pointer,s_no_anim____i_006473b4,VID_NOANIM);
    TextFileWrite(Pointer,s_window_size____i_0064739c,VID_WindowSize);
    TextFileWrite(Pointer,s_version____i_00647384,SYS_GameVersion);
    TextFileWrite(Pointer,s_turbo____i_0064736c,SYS_Turbo);
    TextFileWrite(Pointer,s_bit_depth____i_00647354,VID_BitDepth);
    TextFileWrite(Pointer,s_windows_volume____i_0064733c,AUD_Volume);
    TextFileWrite(Pointer,s_music_volume____i_00647324,AUD_MusicVolume);
    TextFileWrite(Pointer,s_SFXLevel____i_0064730c,AUD_SFXVolume);
    TextFileWrite(Pointer,s_DialogueLevel____i_006472f4,AUD_DialogueVolume);
    TextFileWrite(Pointer,s_rotor_volume____i_006472dc,AUD_RotorVolume);
    TextFileWrite(Pointer,s_audio_channels____i_006472c4,AUD_Channels);
    TextFileWrite(Pointer,s_terrain_detail____i_006472ac,VID_TerrainQuality);
    TextFileWrite(Pointer,s_object_detail____i_00647294,VID_ObjectQuality);
    TextFileWrite(Pointer,s_texture_res____i_0064727c,VID_TextureQuality);
    TextFileWrite(Pointer,s_water_quality____i_00647264,VID_WaterQuality);
    TextFileWrite(Pointer,s_shadow_quality____i_0064724c,VID_ShadowQuality);
    TextFileWrite(Pointer,s_particle_density____i_00647234,VID_ParticleQuality);
    TextFileWrite(Pointer,s_antialias_mode____i_0064721c,VID_AAQuality);
    TextFileWrite(Pointer,s_foliage____i_00647204,VID_Foliage);
    TextFileWrite(Pointer,s_rotorwash____i_006471ec,VID_RotorWash);
    TextFileWrite(Pointer,s_grouping____i_006471d4,SYS_Grouping);
    TextFileWrite(Pointer,s_disable_vshaders____i_006471bc,VID_VShaders);
    TextFileWrite(Pointer,s_disable_pshaders____i_006471a4,VID_PShaders);
    TextFileWrite(Pointer,s_hud_color_index____i_0064718c,VID_HUDColor);
    TextFileWrite(Pointer,s_hud_detail____i_00647174,VID_HUDDetails);
    TextFileWrite(Pointer,s_NoBlood____i_0064715c,_VID_Blood);
    TextFileWrite(Pointer,s_NoCasings____i_00647144,_VID_Casings);
    TextFileWrite(Pointer,s_NoSmoke____i_00647130,_VID_Smoke);
    TextFileWrite(Pointer,&InsertSpace);
    TextFileWrite(Pointer,s____CONTROLS_0064711c);
    TextFileWrite(Pointer,s_crosshairs____i_00647104,VID_Crosshair);
    TextFileWrite(Pointer,s_crosshairs_color____i_006470ec,VID_CrosshairColor);
    TextFileWrite(Pointer,s_showgun____i_006470d4,VID_ShowGun);
    TextFileWrite(Pointer,s_picinpic____i_006470bc,VID_PNP);
    TextFileWrite(Pointer,&InsertSpace);
    TextFileWrite(Pointer,s____MULTIPLAYER_006470ac);
    TextFileWrite(Pointer,s_mp_eula_accepted____i_00647094,MP_EULA);
    TextFileWrite(Pointer,s_mpattrib____i_0064707c,MP_SessionAttributes);
    TextFileWrite(Pointer,s_mp_gameport____i_00647064,MP_GamePort);
    TextFileWrite(Pointer,s_mp_vonport____i_0064704c,MP_VoicePort);
    TextFileWrite(Pointer,s_mp_usealtnwport____i_00647034,MP_UseAltNWPort);
    TextFileWrite(Pointer,s_join_password_____s__00647018,&MP_JoinPassword);
    TextFileWrite(Pointer,s_host_password_____s__00646ffc,&MP_ServerPassword);
    TextFileWrite(Pointer,s_team_password_____s__00646fe0,&MP_TeamPassword);
    TextFileWrite(Pointer,s_game_name_____s__00646fc4,&Net_HostSettings);
    TextFileWrite(Pointer,s_phone_number_____s__00646fa8,&MP_PhoneNumber);
    TextFileWrite(Pointer,s_internet_address_____s__00646f8c,&MP_ServerIPAddress);
    TextFileWrite(Pointer,s_mp_service____i_00646f74,MP_ServiceType);
    TextFileWrite(Pointer,s_mp_difficulty____i_00646f5c,MP_Difficulty);
    TextFileWrite(Pointer,s_mp_gametype____i_00646f44,MP_GameType);
    TextFileWrite(Pointer,s_maxplayers____i_00646f2c,MP_MaxPlayers);
    TextFileWrite(Pointer,s_dedicated____i_00646f14,MP_DedicatedServer);
    TextFileWrite(Pointer,s_com_port____i_00646efc,MP_ComPort);
    TextFileWrite(Pointer,s_baud_rate____i_00646ee4,MP_BaudRate);
    TextFileWrite(Pointer,s_max_team_lives____i_00646ecc,MP_MaxTeamLives);
    TextFileWrite(Pointer,s_max_kills____i_00646eb4,MP_ScoreLimit);
    TextFileWrite(Pointer,s_team_req____i_00646e9c,MP_TeamPreference);
    TextFileWrite(Pointer,s_startdelay____i_00646e84,MP_StartDelay);
    TextFileWrite(Pointer,s_destroybuild____i_00646e6c,MP_DestroyBuild);
    TextFileWrite(Pointer,s_hostrequiresnovaworldlogin____ld_00646e48,MP_RequireNovaLogin);
    TextFileWrite(Pointer,s_oneshotonekill____ld_00646e30,MP_OneShotOneKill);
    TextFileWrite(Pointer,s_fatbullets____ld_00646e1c,MP_FatBullets);
    TextFileWrite(Pointer,s_nwisptype____ld_00646e08,MP_ConnectionType);
    TextFileWrite(Pointer,s_lanmode____ld_00646df8,MP_LanMode);
    TextFileWrite(Pointer,s_allowcustomskins____ld_00646de0,MP_AllowCustomSkins);
    TextFileWrite(Pointer,s_servermsg_____s__00646dc4,&MP_ServerMessage);
    TextFileWrite(Pointer,s_minping____ld_00646dac,MP_MinPing);
    TextFileWrite(Pointer,s_dominpingcheck____ld_00646d94,MP_MinPingCheck);
    TextFileWrite(Pointer,s_maxping____ld_00646d7c,MP_MaxPing);
    TextFileWrite(Pointer,s_domaxpingcheck____ld_00646d64,MP_MaxPingCheck);
    TextFileWrite(Pointer,s_dirtyupstream____ld_00646d4c,MP_DirtyUpstream);
    TextFileWrite(Pointer,s_dirtyupstreampost____ld_00646d30,MP_DirtyUpstreamPost);
    TextFileWrite(Pointer,s_deathmes____i_00646d18,MP_DeathMessage);
    TextFileWrite(Pointer,s_numallowablefriendlykills____ld_00646cf4,MP_MaxFF);
    TextFileWrite(Pointer,s_replay____i_00646cdc,MP_MapCycle);
    TextFileWrite(Pointer,s_time_limit____i_00646cc4,MP_TimeLimit);
    TextFileWrite(Pointer,s_koth_limit____i_00646cac,MP_KOTHZoneTimer);
    TextFileWrite(Pointer,s_timeout____i_00646c94,MP_RespawnTime);
    TextFileWrite(Pointer,s_mp_numteams____i_00646c7c,MP_NumTeams);
    TextFileWrite(Pointer,s_showtags____i_00646c64,MP_ShowTags);
    TextFileWrite(Pointer,s_contest____i_00646c4c,MP_Contest);
    TextFileWrite(Pointer,s_flagreturntime____i_00646c34,MP_FlagReturnTime);
    TextFileWrite(Pointer,s_level_restricted____i_00646c1c,MP_LevelRestricted);
    TextFileWrite(Pointer,s_min_level____i_00646c04,MP_MinPing);
    TextFileWrite(Pointer,s_max_level____i_00646bec,MP_MaxPing);
    TextFileWrite(Pointer,s_ping____i_00646bd4,MP_PingCheck);
    TextFileWrite(Pointer,s_sendplayerlist____ld_00646bbc,MP_SendPlayerList);
    TextFileWrite(Pointer,s_teamchange_time____ld_00646ba4,MP_TeamChangeTime);
    TextFileWrite(Pointer,&InsertSpace);
    TextFileWrite(Pointer,s____MAP_00646b9c);
    TextFileWrite(Pointer,s_map_infrared____i_00646b84,MAP_Infrared);
    TextFileWrite(Pointer,s_map_iff____i_00646b6c,MAP_IFF);
    TextFileWrite(Pointer,s_map_AWAC____i_00646b54,MAP_AWAC);
    TextFileWrite(Pointer,&InsertSpace);
    TextFileWrite(Pointer,s____SYSTEM_00646b48);
    TextFileWrite(Pointer,s_player_index____i_00646b30,SYS_PlayerIndex);
    TextFileWrite(Pointer,s_preempt_pff____i_00646b18,SYS_PreEmptPff);
    TextFileWrite(Pointer,s_whichbrowser____i_00646b00,SYS_BrowserType);
    TextFileWrite(Pointer,s_country_____s__00646ae4,&MP_CountryCode);
    TextFileWrite(Pointer,s_msg_____s__00646ac8,&MP_Message);
    TextFileWrite(Pointer,s_red_password_____s__00646aac,&MP_RedPassword);
    TextFileWrite(Pointer,s_blue_password_____s__00646a90,&MP_BluePassword);
    TextFileWrite(Pointer,s_yellow_password_____s__00646a74,&MP_YellowPassword);
    TextFileWrite(Pointer,s_violet_password_____s__00646a58,&MP_VioletPassword);
    TextFileWrite(Pointer,s_mp_verbose____i_00646a40,SYS_Verbose);
    TextFileWrite(Pointer,s_play_exit_credits____i_00646a24,SYS_PlayCredits);
    TextFileWrite(Pointer,s_mp_NoCharAbilities____i_00646a08,MP_NoCharacterAbilities);
    TextFileWrite(Pointer,s_mp_NoCrossHairSpread____i_006469ec,MP_NoCrosshairSpread);
    TextFileWrite(Pointer,s_mp_NoScopeDrift____i_006469d4,MP_NoScopeDrift);
    TextFileWrite(Pointer,s_mp_NoWeaponRecoil___i_006469bc,MP_NoRecoil);
    TextFileWrite(Pointer,s_mp_gpsicons____i_006469a4,MP_GPSIcons);
    TextFileWrite(Pointer,s_mp_wind____i_0064698c,MP_EnvironmentWind);
    TextFileWrite(Pointer,s_mp_DroppedWeaponDisappear____i_0064696c,MP_DroppedWPNDisappear);
    TextFileWrite(Pointer,s_mp_NoDropWeapons____i_00646954,MP_NoDropWeapons);
    TextFileWrite(Pointer,s_mp_NoRespawnWithPrimary____i_00646934,MP_NoRespawnPrimary);
    TextFileWrite(Pointer,s_mp_ServerGamePort____i_0064691c,MP_ServerGamePort);
    TextFileWrite(Pointer,s_mp_ClientGamePort____i_00646904,MP_ClientGamePort);
    TextFileWrite(Pointer,s_AltLock____i_006468f0,MP_AltLock);
    TextFileWrite(Pointer,s_AltLockType____i_006468dc,MP_AltLockType);
    TextFileWrite(Pointer,&InsertSpace);
    TextFileClose(Pointer);
  }
  return;
}

