#pragma once

#include <windows.h>

namespace borderless_gamma {

// Uses the gamma ramp generated by the game for its D3D8 device and applies it
// to the display while borderless mode has focus.
bool Initialize(bool enabled);
void HandleFocusGained(HWND window, const char* trigger);
void HandleFocusLost(const char* trigger);
void HandleDisplayChanged(HWND window, const char* trigger);
void Poll(HWND window);
void Shutdown();

}  // namespace borderless_gamma
