#include "oval_spin_map.h"

#include <windows.h>

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>

#include "logger.h"

namespace oval_spin_map {
namespace {
// DrawSpinMap() submits its indexed 32-segment radial geometry here. This is
// VA 0x00509973 in the supported executable, not the compring.tga draw at
// 0x005035E2.
constexpr uintptr_t kSpinMapIndexedDrawCallRva = 0x00109973;
constexpr uintptr_t kGameDrawPrimitiveRva = 0x001AA0D0;
constexpr uintptr_t kGameDrawIndexedPrimitiveRva = 0x001AA320;
constexpr uintptr_t kHudSpinMapX1Rva = 0x007F6978;
constexpr uintptr_t kHudSpinMapX2Rva = 0x007F697C;
constexpr uintptr_t kHudSpinMapY1Rva = 0x007F6980;
constexpr uintptr_t kHudSpinMapY2Rva = 0x007F6984;
constexpr int kLineStrip = 3;
constexpr int kTriangleList = 4;
constexpr size_t kSegmentCount = 32;
constexpr size_t kSpinMapVertexCount = kSegmentCount + 1;
constexpr size_t kSpinMapIndexCount = kSegmentCount * 3;

// DFBHD's transformed HUD vertex (FVF 0x2C4) has a 40-byte stride.
struct HudVertex {
    float x;
    float y;
    float z;
    float rhw;
    uint32_t diffuse;
    uint32_t specular;
    float u;
    float v;
    float u2;
    float v2;
};
static_assert(sizeof(HudVertex) == 40, "unexpected DFBHD HUD vertex size");

using DrawPrimitiveFn = int(__cdecl *)(int, const HudVertex*, int);
using DrawIndexedPrimitiveFn = int(__cdecl *)(int, const HudVertex*, int,
                                               const uint16_t*, int);

DrawPrimitiveFn g_gameDrawPrimitive = nullptr;
DrawIndexedPrimitiveFn g_gameDrawIndexedPrimitive = nullptr;
uintptr_t g_moduleBase = 0;
bool g_installed = false;

int __cdecl DrawOvalSpinMap(int primitive, const HudVertex* vertices, int vertexCount,
                            const uint16_t* indices, int indexCount) {
    if (primitive != kTriangleList || vertices == nullptr || indices == nullptr ||
        vertexCount != static_cast<int>(kSpinMapVertexCount) ||
        indexCount != static_cast<int>(kSpinMapIndexCount)) {
        return g_gameDrawIndexedPrimitive(primitive, vertices, vertexCount,
                                          indices, indexCount);
    }

    HudVertex oval[kSpinMapVertexCount] = {};
    std::copy(vertices, vertices + kSpinMapVertexCount, oval);

    // Vertex zero is the center generated by DrawSpinMap(). Recalculate every
    // perimeter position from the submitted bounds instead of relying on the
    // game's integer sin/cos results, while retaining all render attributes.
    const float centerX = vertices[0].x;
    const float centerY = vertices[0].y;
    float radiusX = 0.0f;
    for (size_t index = 1; index < kSpinMapVertexCount; ++index) {
        radiusX = std::max(radiusX, std::fabs(vertices[index].x - centerX));
    }

    const int x1 = *reinterpret_cast<const volatile int*>(g_moduleBase + kHudSpinMapX1Rva);
    const int x2 = *reinterpret_cast<const volatile int*>(g_moduleBase + kHudSpinMapX2Rva);
    const int y1 = *reinterpret_cast<const volatile int*>(g_moduleBase + kHudSpinMapY1Rva);
    const int y2 = *reinterpret_cast<const volatile int*>(g_moduleBase + kHudSpinMapY2Rva);
    const float hudWidth = static_cast<float>(std::abs(x2 - x1));
    const float hudHeight = static_cast<float>(std::abs(y2 - y1));
    const float radiusY = hudWidth > 0.0f ? radiusX * hudHeight / hudWidth : 0.0f;

    if (!(radiusX > 0.0f) || !(radiusY > 0.0f)) {
        return g_gameDrawIndexedPrimitive(primitive, vertices, vertexCount,
                                          indices, indexCount);
    }

    constexpr float kTwoPi = 6.28318530717958647692f;
    for (size_t segment = 0; segment < kSegmentCount; ++segment) {
        const float angle = kTwoPi * static_cast<float>(segment) /
                            static_cast<float>(kSegmentCount);
        oval[segment + 1].x = centerX + std::cos(angle) * radiusX;
        oval[segment + 1].y = centerY + std::sin(angle) * radiusY;
    }

    const int result = g_gameDrawIndexedPrimitive(
        primitive, oval, static_cast<int>(kSpinMapVertexCount), indices, indexCount);

    // Draw directly over the real radial submission to make hook activation and
    // the exact geometry boundary unambiguous during testing.
    HudVertex outline[kSegmentCount + 1] = {};
    for (size_t segment = 0; segment < kSegmentCount; ++segment) {
        outline[segment] = oval[segment + 1];
        outline[segment].diffuse = 0xFFFF0000;
        outline[segment].specular = 0;
    }
    outline[kSegmentCount] = outline[0];
    g_gameDrawPrimitive(kLineStrip, outline,
                        static_cast<int>(kSegmentCount + 1));
    return result;
}

bool WriteRelativeCall(unsigned char* callSite, const void* target) {
    const intptr_t displacement = reinterpret_cast<intptr_t>(target) -
                                  reinterpret_cast<intptr_t>(callSite + 5);
    if (displacement < std::numeric_limits<int32_t>::min() ||
        displacement > std::numeric_limits<int32_t>::max()) return false;

    const int32_t relative = static_cast<int32_t>(displacement);
    DWORD oldProtect = 0;
    if (!VirtualProtect(callSite, 5, PAGE_EXECUTE_READWRITE, &oldProtect)) return false;
    callSite[0] = 0xE8;
    memcpy(callSite + 1, &relative, sizeof(relative));
    FlushInstructionCache(GetCurrentProcess(), callSite, 5);
    DWORD ignored = 0;
    VirtualProtect(callSite, 5, oldProtect, &ignored);
    return true;
}
} // namespace

bool Install(bool enabled) {
    if (!enabled) {
        logger::Log("INFO", "OvalSpinMap", "feature disabled");
        return false;
    }
    if (g_installed) return true;

    static_assert(sizeof(void*) == 4, "OvalSpinMap requires a 32-bit build");
    auto* module = reinterpret_cast<unsigned char*>(GetModuleHandleW(nullptr));
    g_moduleBase = reinterpret_cast<uintptr_t>(module);
    auto* callSite = module + kSpinMapIndexedDrawCallRva;
    const unsigned char expected[] = {0xE8, 0xA8, 0x09, 0x0A, 0x00};
    if (memcmp(callSite, expected, sizeof(expected)) != 0) {
        logger::Log("ERROR", "OvalSpinMap",
                    "indexed Spin Map draw signature mismatch address=0x%08lX",
                    reinterpret_cast<unsigned long>(callSite));
        return false;
    }

    g_gameDrawPrimitive =
        reinterpret_cast<DrawPrimitiveFn>(module + kGameDrawPrimitiveRva);
    g_gameDrawIndexedPrimitive = reinterpret_cast<DrawIndexedPrimitiveFn>(
        module + kGameDrawIndexedPrimitiveRva);
    if (!WriteRelativeCall(callSite, reinterpret_cast<const void*>(&DrawOvalSpinMap))) {
        g_gameDrawPrimitive = nullptr;
        g_gameDrawIndexedPrimitive = nullptr;
        logger::Log("ERROR", "OvalSpinMap", "hook installation failed: error=%lu",
                    GetLastError());
        return false;
    }

    g_installed = true;
    logger::Log("INFO", "OvalSpinMap",
                "indexed 32-segment Spin Map hook installed with red outline");
    return true;
}

} // namespace oval_spin_map
